language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libqt4-dev
script: 
  - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd quackleio && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd quacker && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd encodeleaves && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd gaddagize && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd makegaddag && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd makeminidawg && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd quackleio/iotest && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ../..
  - cd test && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
